### ISSUE TITLE
KeyError: 'kid'

### ISSUE THREAD

**Issue by xccount** [parnexcodes/widevine-L3-WEB-DL-Script#27]
I am getting this error with the main method,
```
Traceback (most recent call last):
  File "C:\Users\sdfsdf\Desktop\widevine-L3-WEB-DL-Script-main\webdl.py", line 28, in <module>
    keys += f"--key {config[i]['kid']}:{config[i]['hex_key']} "
KeyError: 'kid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sdfsdf\Desktop\widevine-L3-WEB-DL-Script-main\webdl.py", line 32, in <module>
    keys += f"--key {config[i]['kid']}:{config[i]['hex_key']} "
KeyError: 'kid'
```
need help!

**Comment by xccount** [comment]
here is the key file of widevine-guesser

[https://tmpfiles.org/dl/90410/keys.json](url)

**Comment by NiKoCZ89** [comment]
https://privatebin.net/?ba87374277ec244b#E4fe2HNJqEVYqPL6Jj5dt3JULboSJ2zRagmWtk9oyt1w

**Comment by xccount** [comment]
I am aware of that, but i am getting KeyError: kid, **why?**, what is the fix..
