### ISSUE TITLE
KeyError: 'kid'

### ISSUE THREAD

**Issue by chrisgarland21** [parnexcodes/widevine-L3-WEB-DL-Script#83]
I'm new to coding so this may be a simple issue to resolve... This is the error message I am getting:
-------------
`Traceback (most recent call last):
  File "C:\Users\kevin\Documents\widevine-L3-WEB-DL-Script-main\widevine-L3-WEB-DL-Script-main\webdl.py", line 35, in <module>
    keys += f"--key {config[i]['kid']}:{config[i]['hex_key']} "
KeyError: 'kid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kevin\Documents\widevine-L3-WEB-DL-Script-main\widevine-L3-WEB-DL-Script-main\webdl.py", line 39, in <module>
    keys += f"--key {config[i]['kid']}:{config[i]['hex_key']} "
KeyError: 'kid'`
---------------
I am using a keys.json file obtained in Chrome 94 from Hulu. There are two mpds, I tried swapping them but the same issue occurred. Is this something on my end or something Hulu has changed to break the keys.json file?

**Comment by ErickAlex77** [comment]
I have the same error when trying to download from HBO MAX. I understand that you have to edit the script because each web page is different. But I still don't know how to fix it

**Comment by NiKoCZ89** [comment]
U both wrong edit keys file

**Comment by ErickAlex77** [comment]
Find a possible solution to my problem. Send me the keys.json to try to download it.

**Comment by orezraey** [comment]
> 
> 
> Find a possible solution to my problem. Send me the keys.json to try to download it.

Can I? Trying to download from HBO Max also

**Comment by ErickAlex77** [comment]
> > Find a possible solution to my problem. Send me the keys.json to try to download it.
> 
> Can I? Trying to download from HBO Max also

To download from HBO Max, follow these steps, it takes a while.
https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/issues/24#issuecomment-911298420

**Comment by Essam23** [comment]
@ErickAlex77 You could use this method, it has less steps https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/issues/56#issuecomment-965641211

**Comment by ErickAlex77** [comment]
> @ErickAlex77 You could use this method, it has less steps [#56 (comment)](https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/issues/56#issuecomment-965641211)

Excellent, works very well, thank you very much
